on:
  workflow_dispatch:

name: docker.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - uses: docker/setup-qemu-action@v3
      - name: Set up library path
        run: |
          echo "R_LIBS_USER=${RUNNER_TEMP}/Library" >> ${GITHUB_ENV}
          mkdir -p "${RUNNER_TEMP}/Library"
      - name: Pull and start container
        run: |
          docker pull ghcr.io/r-hub/containers/s390x
          docker run -d --name s390x \
            -v`pwd`:/root \
            -v"$R_LIBS_USER:/usr/local/lib/R/site-library" \
            ghcr.io/r-hub/containers/s390x \
            bash -c 'while true; do sleep 10000; done'
      - name: Set up remote Rscript
        run: |
          echo > /usr/local/bin/Rscript.c '
          #include <stdlib.h>
          #include <string.h>
          int main(int argc, char **argv) {
            char cmd[8192];
            if (argc <= 1) return 0;
            cmd[0] = 0;
            strncat(cmd, "Rscript2 ", sizeof(cmd)-1);
            strncat(cmd, argv[1], sizeof(cmd)-1);
            return system(cmd);
          }
          '
          gcc -o /usr/local/bin/Rscript /usr/local/bin/Rscript.c
          echo > /usr/local/bin/Rscript2 '
          #! /bin/bash
          set -e
          docker exec -i -w /root -e"R_LIB_FOR_PAK=/usr/lib/R/library" s390x < $1 \
            R --no-save -q
          '
          chmod 775 /usr/local/bin/Rscript2
      - name: Test R in container
        run: |
          getRversion()
          R.version[["platform"]]
          dir()
        shell: Rscript {0}

      - name: Try manual sessioninfo install
        run: |
          pak::pkg_install("cli")
          install.packages("sessioninfo", repos = "https://cloud.r-project.org")

      - uses: r-lib/actions/setup-r-dependencies@feature/container
        with:
          pak-version: none
