on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - uses: docker/setup-qemu-action@v3
      - run: |
          echo "R_LIBS_USER=${RUNNER_TEMP}/Library" >> ${GITHUB_ENV}
      - run: |
          docker pull ghcr.io/r-hub/containers/s390x
          docker run -d --name s390x -v`pwd`:/root ghcr.io/r-hub/containers/s390x \
            bash -c 'while true; do sleep 10000; done'
      - run: |
          echo <<END > /usr/local/bin/Rscript
          #! /bin/bash
          docker exec -i minimal < $1 bash -
          END
          chmod 775 /usr/local/bin/Rscript
      - run: |
          getRversion()
          R.version
        shell: Rscript {0}

      - run: |
          docker exec s390x ps
