on:
  workflow_dispatch:

name: RMV

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: pkgcache
          dependencies: "'hard'"
          
      - name: Test RMV
        run: |
          curl::curl_fetch_disk('https://community.r-multiverse.org/src/contrib/PACKAGES.gz', tmp <- tempfile())
          read.dcf(tmp)
          options(repos = c(RMV="https://community.r-multiverse.org",CRAN="https://cloud.r-project.org"))
          pkgcache::meta_cache_list()
          pkgcache::meta_cache_list("nanonext")
          pak::meta_list("nanonext")
        shell: Rscript {0}
